# Perfil padrão (desenvolvimento)
spring:
  application:
    name: MyFinances
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/myfinances}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      timeout: 30m

# Configurações específicas da aplicação
app:
  name: MyFinances
  version: 1.0.0
  upload:
    dir: ${UPLOAD_DIR:./uploads}
  security:
    remember-me-key: ${REMEMBER_ME_KEY:mySecretKey}
    jwt:
      secret: ${JWT_SECRET:myJwtSecretKey}  # Para Android futuro
      expiration: ${JWT_EXPIRATION:86400000} # 24 horas

# Logging
logging:
  level:
    com.example.myfinances: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Perfil de desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false

logging:
  level:
    com.example.myfinances: DEBUG
    org.springframework.web: DEBUG

---
# Perfil de produção
spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true
  jpa:
    show-sql: false
  flyway:
    enabled: true

logging:
  level:
    com.example.myfinances: WARN
    root: WARN

# CORS Configuration para Android (futuro)
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true