# Perfil padrão (desenvolvimento)
spring:
  application:
    name: MyFinances
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/MyFinances}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 1800  # 30 minutes in seconds
        http-only: true
        secure: false  # Set to true in production with HTTPS
      tracking-modes: cookie
      persistent: false

# Configurações específicas da aplicação
app:
  name: MyFinances
  version: 1.0.0
  upload:
    dir: ${UPLOAD_DIR:./uploads}
  security:
    remember-me-key: ${REMEMBER_ME_KEY:change-this-key-in-production}
    jwt:
      secret: ${JWT_SECRET:change-this-secret-in-production}  # MUST be set in environment
      expiration: ${JWT_EXPIRATION:86400000} # 24 horas

# Logging
logging:
  level:
    com.example.myfinances: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_PARAMS_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{userId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{userId}] %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:./logs/myfinances.log}
    max-size: 10MB
    max-history: 30

---
# Perfil de desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DATABASE_URL:jdbc:postgresql://localhost:5432/MyFinances}
    username: ${DEV_DATABASE_USERNAME:admin}
    password: ${DEV_DATABASE_PASSWORD:sammy2009}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true

server:
  servlet:
    session:
      persistent: false
      timeout: 5m  # Shorter timeout for dev
      cookie:
        max-age: 300  # 5 minutes for dev

logging:
  level:
    com.example.myfinances: DEBUG
    org.springframework.web: DEBUG

---
# Perfil de produção
spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true
  jpa:
    show-sql: false
  flyway:
    enabled: false

logging:
  level:
    com.example.myfinances: WARN
    root: WARN

# CORS Configuration para Android (futuro)
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true